# Site settings
title:       Sebs Blog
email:       sebastian.schoenherr@i-med.ac.at
author:      Sebastian Sch√∂nherr
description: ""
baseurl:     ""
url:         "http://seppinho.github.io"

# Google analytics
google_analytics: UA-59813715-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: seppinhoblog

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: seppinho
bitbucket_username:
stackoverflow_id:
twitter_username: seppinho
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post:'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
